insert into xr_g_dictionary(original,translate)values
('cotton','хлопок'),
('pack','упаковка'),
('Machine washable','Машинная стирка'),
('leather','кожа'),
('mm wide','мм ширина'),
('Waist Sizes   ""','Обхват груди  ""'),
('Reversible buckle','Двухсторонняя пряжка'),
('Italian leather','Итальянская кожа'),
('polypropylene','полипропилен'),
('elastodiene','эластан'),
('Tanned in Italy','Выделано в Италии'),
('silk face','Шелковая лицевая часть'),
('merino wool reverse','Изнанка из шерсти мериноса'),
('Dry clean only','Только химчистка'),
('cashmere','кашемир'),
('merino wool','шерсть мериносов'),
('Woven in Scotland','Соткано в Шотландии'),
('Leather','Натуральная кожа'),
('Wipe with a damp cloth','Протирать влажной тканью'),
('wool','шерсть'),
('Sizes','Размеры'),
('Specialist dry clean only','Только химчистка'),
('Woven in England','Соткано в Англии'),
('polyamide','полиамид'),
('elastane','эластан'),
('Comfort toe seam','Мягкие швы'),
('nylon','нейлон'),
('Handlinked toe','Мысок обработан вручную'),
('Comfort welt','Комфортная резинка'),
('Reinforced heel and toe','Усиленная пятка и мысок'),
('linen','лен'),
('polyester','полиэстер'),
('Wooden handle','Деревянная ручка'),
('Span diameter  cm','Диаметр в открытом состоянии  см'),
('Comes with slip cover','Чехол в комплекте'),
('One size','Один размер'),
('Combination fastening','Комбинированная застежка'),
('Closed and supportive front panel','Закрытая передняя часть, обеспечивающая поддержку'),
('Elasticated waist','Эластичный пояс'),
('Boxer:  cotton. Socks:  cotton','Трусы:  хлопок. Носки:  хлопок'),
('Gift box includes:  pair of boxers,  pairs of socks.','Подарочная упаковка включает:  пары трусов   пары носков'),
('Trunk:  cotton','Трусы:  хлопок'),
('elastane. Socks:  cotton','эластан. Носки:  хлопок'),
('Gift box includes:  pair of trunks,  pairs of socks.','Подарочная упаковка включает:  пары трусов   пары носков'),
('viscose','вискоза'),
('Dimensions:  mm x  mm x  mm','Размеры: мм х мм х мм'),
('Dimensions: . mm x . mm x . mm','Размеры: мм х мм х мм'),
('Dimensions:  mm x  mm x . mm','Размеры: мм х мм х мм'),
('Palladium plated with enamel insert','Покрытие из палладиума с эмалевой вставкой'),
('Charles Tyrwhitt logo on the reverse','Логотип Charles Tyrwhitt на обороте'),
('Supplied in a cufflink box','Поставляется в коробке'),
('Silver plated with enamel insert','Покрытие из серебра с эмалевой вставкой'),
('Silver plated','Покрытие из серебра'),
('Silver plated with motherofpearl and onyx insert','Покрытие из серебра со вставкой из перламутра и оникса'),
('Reversible','Двусторонний'),
('Palladium plated','Покрытие из палладиума'),
('Rose gold plated','Покрытие из розового золота'),
('Silk insert','Вставка из шелка'),
('Brass','Латунь'),
('pairs','пары'),
('Prevents curling collars','Предохраняет от сминания воротника'),
('Charles Tyrwhitt embossed','Выдавлена надпись Charles Tyrwhitt'),
('mm x  mm','мм х мм'),
('pair','пара'),
('Ruthenium','Рутений'),
('Clip fastening','Крепление на зажиме'),
('Buttondown collar','Воротник с пуговицами'),
('Classic fit','Классический покрой'),
('Non-iron','Немнущаяся'),
('Available in single cuff with twobuttons','Доступно с однослойными манжетами с двумя пуговицами'),
('Chest pocket as standard','Нагрудный карман в базовой комплектации'),
('Split back yoke and back pleats for an excellent fit','Кокетка и боковые складки сзади для идеальной посадки'),
('Extra slim fit','Сильно зауженый покрой'),
('Available in single cuff, with twobuttons','Доступно с однослойными манжетами с двумя пуговицами'),
('No chest pocket','Без нагрудного кармана'),
('Slim fit','Зауженый покрой'),
('Contrast inner collar stand and inner cuff','Контрастные вставки на внутренней части воротника и манжет'),
('Split back yoke and back box pleat for an excellent fit','Кокетка и складка по центру спины для идеальной посадки'),
('Garment washed for a softer touch','Специально обработано для придания мягкости'),
('Split back yoke and back darts for an excellent fit','Кокетка и вытачки сзади для идеальной посадки'),
('Classic collar','Классический воротник'),
('Available in curved single cuff with twobuttons','Доступно с однослойными скругленными манжетами с двумя пуговицами'),
('Contrast detail under placket and inner cuff','Контрасные детали на внутренней части планки и манжет'),
('Available in single curved adjustable cuff, with twobuttons','Доступно с однослойными скругленными регулируемыми манжетами с двумя пуговицами'),
('Herringbone tape at back neck and inner cuff','Тесьма на внутренней части воротника и манжет'),
('Centre back box pleat','Складка по центру спины'),
('Side back pleats','Боковые складки сзади'),
('Contrast binding at back neck','Контрастная обшивка на внутренней части воротника'),
('Contrast gusset','Контрастная ластовица'),
('Machine Washable','Машинная стирка'),
('Contrast binding at back neck and inside cuff','Контрастная обшивка на внутренней части воротника и манжет'),
('Contrast detail at back neck, inner cuff and placket','Контрастные детали на внутренней части воротника, манжет и планки'),
('Egyptian cotton','Египетский хлопок'),
('Semicutaway collar','Полуподрезанный воротник'),
('Available in curved cuff, with onebutton','Доступно со скругленными манжетами с одной пуговицей'),
('Complimentary brass collar stiffeners','Дополнительные латунные вставки для повышения жесткости воротника'),
('Available in single cuff with onebutton','Доступно с однослойными манжетами с одной пуговицей'),
('Complimentary brass collar stiffeners, contrast back neck and cuff tape and contrast gusset','Дополнительные латунные вставки для повышения жесткости воротника, контрастная лента на внутренней части воротника и манжет, контрастная ластовица'),
('Contrast back neck and cuff tape and contrast gusset','Контрастная лента на внутренней части воротника и манжет, контрастная ластовица'),
('Available in square double cuff','Доступно с прямыми двухслойными манжетами'),
('Complimentary brass collar stiffeners and motherofpearl buttons','Дополнительные латунные вставки для повышения жесткости воротника и перламутровые пуговицы'),
('Wing collar','Воротник бабочка'),
('Cutaway collar','Подрезанный воротник'),
('Available in mitred single cuff with twobuttons or mitred double cuff','Доступно со скошенными однослойными манжетами с двумя пуговицами или скошенными двуслойными манжетами'),
('Peached finish for a softer touch','Обработано для придания мягкости'),
('Available in single cuff with twobuttons or square double cuff','Доступно с однослойными манжетами с двумя пуговицами или прямыми двуслойными манжетами'),
('Short sleeves','Короткие рукава'),
('Pocket as standard','Карман в комплекте'),
('Available in mitred single cuff with twobuttons or square double cuff','Доступно со скошенными однослойными манжетами с двумя пуговицами или прямыми двуслойными манжетами'),
('Available in double cuff or single cuff, with twobuttons','Доступно с двуслойными или однослойными манжетами с двумя пуговицами.'),
('Supercare finish to improve colour fastness, reduce fading, pilling and shrinkage','Специальная обработка для увелтчения прочности окраски, уменьшения выцветания, пилинга и усадки'),
('Twobutton placket','Планка с двумя пуговицами'),
('Knitted collar and rib collar and cuff','Воротник и манжеты, связанные в резинку'),
('Long sleeves','Длинные рукава'),
('Garment washed for a softer touch and shrinkage control','Специально обработано для придания мягкости и контроля усадки'),
('Concealed fastening','Потайная застежка'),
('Rib collar and cuff','Ворот и манжеты в резинку'),
('Vneck','V-образный ворот'),
('Contrast detail inside neckline','Контрастная вставка по линии шеи'),
('Crew neck','Ворот с круглым вырезом'),
('Button neck','Воротник на пуговицах'),
('Threebutton fastening','Застежка на трех пуговицах'),
('Zip neck','Воротник на молнии'),
('Two way zip','Двусторонняя застежка молния'),
('Alcantara ® trim on zip neck','Отделка Alcantara ® на молнии'),
('Soft finish','Мягкая отделка'),
('Single breasted with fourbutton fastening','Однобортный с застежкой на четырех пуговицах'),
('Working button cuff','Функциональная пуговица на манжете'),
('Quilted','Простеганый'),
('Internal pocket','Внутреннмй карман'),
('Corozo nut buttons and elbow patch','Пуговицы из ореха Коросо и нашивки на локтях'),
('Made in England','Сделано в Англии'),
('Lining: Red, white and navy multi check design','Подкладка: красно сине белая клетка'),
('Lining: Navy melange with grey overcheck','Подкладка: темно-синий меланж с серой окантовкой'),
('One way zip','Односторонняя застежка молния'),
('Lining:  cotton in blue check','Подкладка:  хлопок в синюю клетку'),
('Single breasted with stud fastening','Однобортный с застежкой на кнопках'),
('Twin back vents','Двойной шлиц сзади'),
('Patch side pockets with side entry handwarmer pockets and patch chest pockets','Накладные карманы сбоку свходом для согревания рук и накладные карманы на груди'),
('Brass studs','Латунные кнопки'),
('Lining:  cotton in blue','Подкладка: хлопок синего цвета'),
('Single breasted and zip through','Однобортный с застежкой молния'),
('Rib cuff','Манжеты в резинку'),
('Slant pocket with button through flap','Скошенный карман с пуговицей на клапане'),
('Corozo nut buttons','Пуговицы из ореха Коросо'),
('Lining:  viscose in burgundy','Подкладка:  вискоза цвета бургундского'),
('Single breasted with threebutton fastening','Однобортный с застежкой на трех пуговицах'),
('Working fourbutton cuff','Четыре функциональные пуговицы на манжете'),
('Canvas chest piece construction and single back vent','Конструкция передней части с бортовкой и один шлиц сзади'),
('Straight flap pockets with outbreast welt pocket','Прямые карманы с клапаном и врезной нагрудный карман'),
('Corozo nut buttons and contrast melton undercollar','Пуговицы из ореха Коросо и контрастный подворотник мелтон'),
('Woven in Italy','Соткано в Италии'),
('Lining:  viscose in purple','Подкладка: вискоза сиреневого цвета'),
('Single back vent','Один шлиц сзади'),
('Lining:  viscose twill in coronet blue','Подкладка: вискоза саржевого сплетения цвета королевский синий '),
('Lining:  viscose in silver','Подкладка: вискоза серебристого цвета'),
('Slant pockets','Скошенные карманы'),
('Lining:  viscose in green','Подкладка: вискоза зеленого цвета'),
('Corozo nut buttons and corozo nut buttons','Пуговицы из ореха Коросо'),
('Single breasted with concealed placket','Однобортный со скрытой планкой'),
('Lining:  viscose in sand','Подкладка: вискоза песочного цвета'),
('Lining:  viscose in stone','Подкладка: вискоза цвета камня'),
('Double breasted with fourbutton fastening and eightbuttons showing','Двубортный с восемью пуговицами и застежкой на четырех пуговицах'),
('Horn buttons','Пуговицы из рога'),
('Lining:  polyester','Подкладка: полиэстер'),
('viscose in magenta','вискоза пурпурного цвета'),
('Single breasted with twobutton fastening','Однобортный с застежкой на две пуговицы'),
('Canvas chest piece construction','Конструкция передней части с бортовкой'),
('Slant flap pockets with outbreast welt pocket','Боковые карманы с клапаном и врезной нагрудный карман'),
('Corozo nut buttons and melton undercollar','Пуговицы из ореха Коросо и подворотник мелтон'),
('viscose twill in navy with magneta printed with magneta spot',' вискоза саржевого сплетения пурпурного цвета и вискоза темно-синего цвета в пурпурный горошек'),
('Working button cuffs','Функциональные пуговицы на манжетах'),
('viscose in navy','вискоза темно-синего цвета'),
('viscose twill in navy with navy printed with magneta spot',' вискоза саржевого сплетения темно-синего цвета и вискоза темно-синего цвета в пурпурный горошек'),
('Butterfly lining:  polyester','Подкладка Баттерфляй:  полиэстер'),
('viscose in cream','вискоза цвета сливок'),
('Twobutton fastening','Застежка на двуз пуговицах'),
('viscose in fig','вискоза цвета инжира'),
('Lining:  viscose','Подкладка:  вискоза'),
('acetatein green two tone design',' ацетат, двухтоновый дизайн'),
('Velvet covered buttons','Обтянутые бархатом пуговицы'),
('Soft construction','Мягкая конструкция'),
('viscose in burgundy','вискоза цвета бургундского'),
('Wool','Шерсть'),
('Cotton','Хлопок'),
('Cashmere','Кашемир'),
('Lining:  viscose in light blue','Подкладка: вискоза светло голубого цвета'),
('Corozo nut buttons and contrast undercollar','Пуговицы из ореха Корсо и контрастный подворотничок'),
('Butterfly lining:  viscose in magenta','Подкладка Баттерфляй: вискоза пурпурного цвета'),
('Butterfly lining:  viscose in navy','Подкладка Баттерфляй: вискоза темно-синего цвета'),
('viscose in purple','вискоза фиолетового цвета'),
('viscose in blue','вискоза голубого цвета'),
('Half lined:  viscose in burgundy','Полуподкладка: вискоза цвета бургундского'),
('Part lined:  polyester','Часть подкладки: полиэстер'),
('Unstructured jacket','Пиджак без бортовки'),
('Cedar wood','Древесина кедра'),
('Cedar is a natural wood that aids the absorption of moisture','Натуральная древесина кедра способствует впитыванию влаги'),
('Maintains the shape of your shoes and prolongs their life','Помогает сохранить форму обуви и продляет ее срок службы'),
('Reduces creases in flex areas for comfort','Уменьшает складки в сминающихся зонах для повышения комфорта'),
('Neutral shoe polish','Безцветный крем для обуви'),
('Black shoe polish','Черный крем для обуви'),
('Polishing cloth','Ткань для полировки обуви'),
('Dark and light bristle polishing brush','Щетка для обуви из темной и светлой щетины'),
('Two applicator brushes','Две щетки для нанесения крема'),
('Shoe horn','Рожок для обуви'),
('Cleans, nourishes and protects smooth leather','Очищает, питает и защищает гладкую кожу'),
('Restores all colours of delicate leather','Восстанавливает цвет тонкой кожи'),
('Only to be used on waxy, smooth, patent or reptile leather uppers','Использовать только для верха из вощеной, гладкой, лакированой кожи или кожи рептилий'),
('Removes and prevents unpleasant shoe odours','Удаляет и предотвращает появление неприятных запахов обуви'),
('Suitable for all footwear','Подходит для любой обуви'),
('Ideal for applying polish and buffing to a shine','Идеально подходит для нанесения и полировки до блеска'),
('Round laces','Круглые шнурки'),
('cm in length','см в длину'),
('Made in Spain','Сделано в Испании'),
('Leather upper','Кожаный верх'),
('Lining: Leather','Подкладка: Натуральная кожа'),
('Sole: Other material','Подошва: Различные материалы'),
('Blake stitched construction','Крепление подошвы: "Blake" (без ранта)'),
('Made in Portugal','Сделано в Португалии'),
('Specialist shoe care products: SHANON, SHANTL, SHANTL, SHANON, SHANON','Специальные средства по уходу за обувью: SHANON, SHANTL, SHANTL, SHANON, SHANON'),
('Specialist shoe care products: SHANON, SHABRN, SHANTL, SHANTL, SHANON, SHANON','Специальные средства по уходу за обувью: SHANON, SHABRN, SHANTL, SHANTL, SHANON, SHANON'),
('Leather and textile lined','Подкладка: Кожа и текстильные материалы'),
('Other material sole','Подошва из различных материалов'),
('Use specialist shoe care cleaning products only','Используйте только специальные очистки для ухода за обувью'),
('Other material sole with leather arch','Различные материалы подошвы и кожаный свод'),
('Lining: Leather and textile','Подкладка: Кожа и текстильные материалы'),
('Sole: Leather &amp; other materials','Подошва: Кожа и другие материалы'),
('Goodyear welted construction','Крепление подошвы: "Goodyear welted" (с рантом)'),
('Specialist shoe care products: SHANON, SHABLK, SHANTL, SHANON, SHANON','Специальные средства по уходу за обувью: SHANON, SHABLK, SHANTL, SHANON, SHANON'),
('Composition: upper  leather, sole  leather and other materials','Верх - кожа, подошва - кожа и другие материалы'),
('Upper made from  leather','Верх из натуральной кожи'),
('Traditional leather sole with rubber heel tip','Традиционная кожаная подошва и резиновый каблук'),
('Unlined','Без подкладки'),
('Moccasin','Мокасины'),
('Specialist shoe care products: SHANON, SHABLK, SHANTL, SHANTL, SHANON, SHANON','Специальные средства по уходу за обувью: SHANON, SHABLK, SHANTL, SHANTL, SHANON, SHANON'),
('Leather sole with other material heel','Кожаная подошва и другие материалы для изготовления каблука'),
('Specialist shoe care products: SHANON, SHABRN, SHANTL, SHANON, SHANON','Специальные средства по уходу за обувью: SHANON, SHABRN, SHANTL, SHANON, SHANON'),
('Leather lined','Кожаная подкладка'),
('Suede leather upper','Верх из натуральной замши'),
('Leather sole with other material heel tip','Кожаная подошва и другие материалы для изготовления каблука'),
('Sole: Other materials and leather','Подошва: кожа и другие материалы'),
('Specialist shoe care products: SHANON, SHANON','Специальные средства по уходу за обувью: SHANON'),
('Made in Italy','Сделано в Италии'),
('Rubber sole','Резиновая подошва'),
('Lining: Leather. Comfort inner sole','Подкладка: Кожа. Комфортная стелька.'),
('Full grain calf leather upper','Верх из телячьей кожи'),
('Sole: Leather','Подошва: кожа'),
('English hand lasted sewn shoes','Ботинки прострочены на английский манер'),
('Cemented sole construction','Клеевой способ крепления подошвы'),
('Specialist shoe care products: SHANON','Специальные средства по уходу за обувью: SHANON'),
('Specialist shoe care products: SHANTL, SHANON','Специальные средства по уходу за обувью: SHANTL, SHANON'),
('Super \'s yarn','Шерсть Супер'),
('viscose in light blue','вискоза светло-голубого цвета'),
('Single breasted twobutton fastening','Однобортный с застежкой на двух пуговицах'),
('Canvas chest piece construction and twin back vents','Конструкция с бортовкой (canvas) и двумя шлицами сзади'),
('Corozo nut buttons and contrast stalk loops under lapel','АПуговицы из ореха Коросо и контрастные петли на обратной стороне лацкана'),
('Half lined to knee','Подкладка до колена'),
('Flat front','Прямая передняя часть'),
('Slanted pockets','Наклонные карманы'),
('Belt loops to fit . cm belt','Петли подходят для ремня шириной до см'),
('Single breasted fivebutton fastening','Однобортный с застежкой на пяти пуговицах'),
('Welt pockets','Прорезные карманы'),
('Half lined to the knee','Подкладка до колена'),
('Jetted hip pocket','Боковой карман в шве'),
('viscose in lilac','вискоза сиреневого цвета'),
('Slanted flap pockets with outbreast welt pocket','Боковые карманы с клапанами и прорезной нагрудный карман'),
('viscose in dark grey','вискоза темно-серого цвета'),
('viscose in green','вискоза зеленого цвета'),
('Belt loops to fit up to . cm width belt','Петли подходят для ремня шириной до см'),
('viscose in black','вискоза черного цвета'),
('viscose in charcoal','вискоза угольного цвета'),
('Single breasted onebutton fastening','Однобортный с застежкой на одной пуговице'),
('Canvas chest piece construction and no back vents','Конструкция с бортовкой (canvas) и двумя шлицами сзади'),
('Satin lapel and satin covered buttons','Атласные лацканы и обтянутые атласом пуговицы'),
('External side adjusters with buckle','Боковая регулировка ширины с пряжкой'),
('Single breasted fourbutton fastening','Однобортный с застежкой на четырех пуговицах'),
('viscose twill in teal','вискоза саржевого сплетения изумрудного цвета'),
('Half canvas chest piece construction','Конструкция с частичной бортовкой (half-canvas)'),
('Lining:  viscose in split colours','Подкладка: вискоза разных цветов'),
('Slanted pockets, ticket pocket left hand side, with flaps and outbreast welt pocket','Наклонные карманы, карман для билетов на левой стороне с клапанами и нагрудный прорезной карман'),
('Slanted pocket with ticket pocket and outbreast welt pocket','Наклонные карманы с карманом для билетов и нагрудный прорезной карман'),
('Double breasted threebutton front','Двубортный с тремя пуговицами'),
('Welt side pockets','Прорезные боковые карманы'),
('Half canvas construction and twin back vents','Конструкция с частичной бортовкой (half-canvas) и двумя шлицами сзади'),
('Lining:  viscose in navy','Подкладка: вискоза темно-синего цвета'),
('Double breasted with threebutton fastening and sixbuttons showing','Двубортный с шестью видимыми пуговицами и застежкой на три'),
('super s wool','Высококачественная шерсть'),
('Lining:  viscose in dark grey','Подкладка: вискоза темно-серого цвета'),
('Double breasted with twobutton fastening and sixbuttons showing','Двубортный с шестью видимыми пуговицами и застежкой на две'),
('Slanted welt pockets','Наклонные прорезные карманы'),
('Lining:  viscose in natural','Подкладка: вискоза натурального цвета'),
('Lining:  viscose in cream','Подкладка: вискоза кремового цвета'),
('Woven in Ireland','Соткано в Ирландии'),
('silk','шелк'),
('Hand finished','Ручная обработка'),
('Gift box available at checkout','В корзине доступен заказ подарочной упаковки'),
('cm blade width','см ширина'),
('cm length','см длина'),
('. cm blade width','см ширина'),
('Branded Union Jack detail at the back of the tip','Флаг Великобритании на обратной стороне'),
('cm x  cm','см х см'),
('Single pleat','Один защип'),
('Welt pockets at the back','Прорезные задние карманы'),
('Side entry pockets','Боковые карманы'),
('Zip fly with hook and bar fastener. Button at waistband and internal french bearer','Гульфик на молнии с крючком и французской застежкой'),
('Belt loops to fit  cm belt','Петли подходят для ремня шириной см'),
('Garment washed with a peach finish. Shrinkage control and designed to soft fade','Специально обработано для придания мягкости. Контроль усадки. Крой, обеспечивающий мягкое облегание. '),
('Jet pockets at the back','Прорезные карманы сзади'),
('Zip fly with hook and bar fastener at waistband, and internal french bearer','Гульфик на молнии с крючком и французской застежкой'),
('pocket','карман'),
('pockets','карманов'),
('Zip fly with button at waistband','Гульфик на молнии с пуговицей на поясе'),
('Garment washed for a softer touch. Shrinkage control and designed to soft fade','Специально обработано для придания мягкости. Контроль усадки. Крой, обеспечивающий мягкое облегание. '),
('Semifitted','Полуприталенный крой'),
('Button fastening','Застежка на пуговицах'),
('extra fine merino','тонкая шерсть мериноса'),
('Loose fit','Свободная посадка'),
('Waterfall front','Ниспадающая передняя часть без застежки'),
('modal','модал'),
('Available in square single cuff with twobuttons','Доступно с прямыми однослойными манжетами на две пуговицы'),
('Boat neck','Воротник лодочка'),
('length sleeves','длина рукава'),
('Zip fastening','Застежка "молния"'),
('cm side splits at hem','см отделка по нижнему краю'),
('Water repellent finish','Водотталкивающее покрытие'),
('Princess line seams','Крой "Принцесса"'),
('Twobutton rounded single cuff','Однослойные скругленные манжеты с двумя пуговицами'),
('Single patch pocket','Один накладной карман'),
('Round collar','Скругленный воротник'),
('Tab sleeves','Подвернутый рукав'),
('Pleat detail from neck line','Плиссировка по линии воротника'),
('Capped sleeves','Короткий цельнокроенный рукав'),
('Dimensions:  cm x  cm','Размеры: см х см'),
('Contrast inner collar stand','Контрасная внутренняя сторона воротника'),
('Contrast detail at back neck, gauntlet and inner cuff','Контрастные вставки на внутренней стороне воротника, манжет и в разрезе рукава'),
('Contrast detail at back neck and inner cuff','Контрастные вставки на внутренней стороне воротника и манжет'),
('Herringbone tape at back neck and inner cuff and contrast gusset','Тесьма на внутренней стороне воротника и манжет, контрастная ластовица'),
('Contrast detail at back neck, inner cuff and gusset','Контрастные вставки на внутренней стороне воротника, манжет и на ластовице'),
('Extreme cutaway collar','Сильно подрезанный воротник'),
('Available in mitred single cuff with twobuttons','Доступно со срезанными однослойными манжетами на две пуговицы'),
('Pima cotton','Пима-хлопок'),
('Sixbutton fastening','Застежка на шести пуговицах'),
('Half lined:  viscose in blue','Полуподкладка: голубая вискоза'),
('Melton undercollar','Подворотник мелтон'),
('Unstructured construction','Неструктурированная конструкция'),
('Leather and suede upper','Верх из кожи и замши'),
('Available in mitred single cuff with two-buttons or square double cuff','Доступно со скошенными однослойными манжетами с двумя пуговицами или с прямыми двухслойными манжетами'),
('Concealed placket','Скрытая планка'),
('twill navy','твил темно-синий'),
('twill off-white','твил белый'),
('poplin berry stripe','поплин ягодный в полоску'),
('poplin indigo stripe','поплин индиго в полоску'),
('poplin green and blue check','поплин в зелено-синюю клетку'),
('poplin navy check','поплин в темно-синюю клетку'),
('poplin navy and berry check','поплин в ягодно-темно-синюю клетку'),
('poplin sky blue check','поплин в небесно-голубую клетку'),
('grey and sky blue check heather','серая в голубую и вересковую клетку'),
('denim blue washed Oxford','Оксфорд из синего денима, обработанного для смягчения ткани'),
('sky blue washed Oxford','Оксфорд небесно голубого цвета, обработана для смягчения ткани'),
('berry washed Oxford','Оксфорд ягодного цвета, обработана для смягчения ткани'),
('berry check washed Oxford','Оксфорд в клетку ягодного цвета, обработана для смягчения ткани'),
('navy and white check washed Oxford','Оксфорд в темно-синюю и белую клетку, обработана для смягчения ткани'),
('grey stripe washed Oxford','Оксфорд в серую полоску, обработана для смягчения ткани'),
('burgundy and blue check brushed dobby','Добби в сине-бордовую клетку'),
('green and navy check brushed dobby','Добби в зеленую и темно-синюю клетку'),
('semi-cutaway collar','полуподрезанный воротник'),
('semi-cutaway','полуподрезанный'),
('button-down collar','воротник с пуговицами'),
('button-down','с пуговицами'),
('luxury marcella white evening','роскошь марколиновые белый вечер'),
('wing collar','воротник бабочка'),
('wing','бабочка'),
('cutaway collar','подрезанный воротник'),
('cutaway','подрезанный'),
('bengal stripe sky blue','в бенгальскую голубую полоску'),
('twill stripe white and sky blue','твил в бело-голубую полоску'),
('poplin white','поплин белый'),
('twill white','твил белый'),
('royal Panama white','Панама цвета королевский белый'),
('short sleeve bengal stripe lilac','с коротким рукавом, лиловая в бенгальскую полоску'),
('grid check pink short sleeve','с коротким рукавом, розовая в крупную клетку'),
('twill pink','твил розовый'),
('twill lilac','твил сиреневый'),
('twill sky blue','твил небесно голубой'),
('micro spot white','белая с мелкими пятнышками'),
('micro spot sky blue','голубая с мелкими пятнышками'),
('short sleeve dobby check navy','Добби с коротким рукавом в темно-синюю клетку'),
('honeycomb sky blue','ткань сотового сплетения голубого цвета'),
('raised stripe navy','выпуклая темно-синяя полоска'),
('Egyptian cotton','Египетский хлопок'),
('Egyptian','Египетский'),
('Black','Черный'),
('twill','твил'),
('business suit jacket','пиджак для делового костюма'),
('Charcoal','Угольный'),
('Navy','Темно-синий'),
('Royal blue','Королевский синий'),
('Airforce blue','Военно-воздушный синий'),
('business suit trousers','брюки для делового костюма'),
('Grey','Серый'),
('check','в клетку'),
('classic fit','классический покрой'),
('end-on-end','Ткань end-on-end'),
('Blue check','В синюю клетку'),
('flannel','фланель'),
('Indigo','Индиго'),
('saxony','саксонская шерсть'),
('Navy check','В темно-синюю клетку'),
('Charcoal stripe','В полоску угольного цвета'),
('shawl collar','воротник-шалька'),
('peak lapel','остроконечные лацканы'),
('Brown check','В коричневую клетку'),
('British Panama','Британская Панама'),
('luxury suit jacket','пиджак для роскошного костюма'),
('Grey check','В серую клетку'),
('luxury suit trousers','брюки для роскошного костюма'),
('British serge','Британский твил'),
('birdseye','ткань birdseye'),
('travel suit jacket','пиджак для дорожного костюма'),
('travel suit trousers','брюки для дорожного костюма'),
('Blue','синий'),
('sharkskin','Королевский синий'),
('travel suit trouser','брюки для дорожного костюма'),
('Black and white','Черно-белый'),
('silk','шелк'),
('neat pattern ready-tied bow','стильный с готовым узлом'),
('puppytooth ready-tied bow','с рисунком "гусиные лапки" и готовым узлом'),
('Gold and navy','Золотой с темно-синим'),
('classic Fleur-de-Lys','классический с рисунком "Цветок лилии"'),
('Navy and white','Темно-синий с белым'),
('Navy and pink','Темно-синий с розовым'),
('Fleur-de-Lys classic','классический с рисунком "Цветок лилии"'),
('Red and sky','Красный и небесный'),
('Royal and pink','Королевский синий и розовый'),
('spot classic','горошек, классический'),
('Berry and sky','Ягодный с небесным'),
('Gold and blue','Золотой с синим'),
('classic spot','классическй в горошек'),
('Pink and blue','Розовый с голубым'),
('block stripe classic','в широкую полоску классический'),
('oval classic','с овальным рисунком классический'),
('circle link classic','с рисунком из окружностей классический'),
('Navy and berry','Темно синий и ягодный'),
('textured stripe classic','текстурированный в полоску классический'),
('blue and navy','голубой c темно-синим'),
('wool','шерсть'),
('luxury Italian geometric','роскошный итальянский с геометрическим узором'),
('Navy and grey','Темно-синий c серым'),
('luxury English triangle slim','роскошный с узором "Английский зигзаг" узкий'),
('Blue and white','Синий c белым'),
('textured luxury','роскошный текстурированный'),
('end-on-end luxury','роскошный из ткани сплетения "end-on-end"'),
('White and navy','Белый с темно-синим'),
('Navy and wine','Темно-синий с винным'),
('mix printed Donegal stripe luxury','со смешанным принтом в полоску в стиле "Донегал" роскошный'),
('navy and brown check tweed look','в темно-синюю и коричневую клетку стилизованный под твид'),
('white plain washed Oxford','Оксфорд белая  гладкая, специально обработанная для придания мякгости'),
('puppytooth royal blue','королевский синий с узором "гусиные лапки"'),
('bengal stripe navy','темно-синий в бенгальскую полоску'),
('multi grid check','в многоцветную клетку'),
('Prince of Wales blue and gold','Принц Уэльский синий с золотом'),
('twill grid check royal blue','твил в клетку королевского синего цвета'),
('twill mid blue','твил синего цвета'),
('royal Panama blue','фасона "Панама" королевского синего цвета'),
('short sleeve sky blue','с коротким рукавом небесно голубого цвета'),
('short sleeve bengal stripe sky blue','с коротким рукавом, синяя в бенгальскую полоску'),
('puppytooth sky blue','небесно голубой с рисунком "гусиные лапки"'),
('short sleeve white','с коротким рукавом белая'),
('honeycomb grey','ткань сотового сплетения серого цвета'),
('honeycomb lilac','ткань сотового сплетения сиреневого цвета'),
('honeycomb mid blue','ткань сотового сплетения синего цвета'),
('honeycomb pink','ткань сотового сплетения розового цвета'),
('honeycomb white','ткань сотового сплетения белого цвета'),
('square textured mid blue','с квадратной текстурой синего цвета'),
('triangle textured royal blue','с треугольной текстурой королевского синего цвета'),
('textured herringbone blue','с текстурой "елочка" синий'),
('windowpane short sleeve indigo','с коротким рукавом в клетку цвета индиго'),
('windowpane short sleeve lilac','с коротким рукавом в клетку лилового цвета'),
('Pima cotton','хлопок Пима'),
('Pima','Пима'),
('Prince of Wales blue','Принц Уэльский синий'),
('Prince of Wales basketweave berry','Принц Уэльский корзинного сплетения ягодного цвета'),
('Prince of Wales basketweave green','Принц Уэльский корзинного сплетения зеленого цвета'),
('Prince of Wales basketweave lilac','Принц Уэльский корзинного сплетения сиреневого цвета'),
('Prince of Wales basketweave sky blue','Принц Уэльский корзинного сплетения небесно-голубого цвета'),
('Prince of Wales silver','Принц Уэльский серебристого цвета'),
('herringbone','в елочку'),
('Silver','Серебряный'),
('Brown','Коричневый'),
('business suit trouser','брюки для делового костюма'),
('Navy stripe','В темно-синюю полоску'),
('Dark grey check','В темно-серую клетку'),
('Midnight blue','Полуночный синий'),
('Blue puppytooth','Синий с узором "гусиные лапки"'),
('Tan check','Светло-коричневый в клетку'),
('British flannel','Британская фланель'),
('thornproof','thornproof'),
('Khaki','Хаки'),
('Ink','Чернильного цвета'),
('Navy and gold','с защитой от истирания'),
('classic double stripe','в классическую двойную полоску'),
('navy and green','темно-синий и зеленый'),
('cotton','хлопок'),
('tartan classic','классический из ткани "шотландка"'),
('black and white','черно-белого цвета'),
('neat pattern classic','с классическим рисунком'),
('luxury English geometric','роскошный с Английским геометрическим рисунком'),
('printed luxury','роскошный с принтом'),
('tie','галстук'),
('shirt','рубашка'),
('suit','костюм'),
('suit trousers','костюмные брюки'),
('suit jacket','костюмный пиджак');
