INSERT INTO `xr_g_dictionary` (`id`, `created`, `lang`, `original`, `translate`, `priority`, `updated`, `status`) VALUES
(NULL, CURRENT_TIMESTAMP, 'fr', 'QUANTITÉ', 'количество', '0', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Je recherche', 'поиск', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Boots', 'ботинки', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Robes', 'Платья', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Vestes', 'Куртки', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Jeans', 'джинсы', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Chaussures', 'обувь', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Lingerie', 'дамское белье', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Bijoux', 'ювелирные изделия', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Maroquinerie', 'изделия из кожи', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Accessoires', 'аксессуары', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Tous les', 'все', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Tout à moins de', 'Все в пределах', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Chemises', 'Рубашки', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Montres', 'Часы', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Vaisselle', 'посуда', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Cuisine', 'варка', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Chambre', 'комната', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Décoration', 'украшение', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Sacoche', 'кринолин', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Ajouter au panier', 'Добавить в корзину', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Recevoir une alerte taille', 'Получить уведомление размер', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Ajouter à ma wishlist', 'Добавить в избранное', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'plus que', 'более', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Choisir une taille', 'Выберите размер', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Nos soldes', 'наши продажи', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Espadrilles', 'эспадрильи', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Chaussons', 'тапки', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Richelieus', 'оксфорды', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Mocassins', 'мокасины', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Derbies', 'дерби', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Sacs', 'мешки', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Rangement', 'расположение', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'categories', 'категории', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Imperméables', 'плащи', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Pantalons', 'брюки', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'BÉBÉ', 'детское', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Fille', 'девушка', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Gants', 'перчатки', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Gilets', 'жилеты', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'VALIDER', 'подтвердить', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'FERMER', 'закрыть', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'COULEURS', 'цвета', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Blanc', 'белый', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Bleu', 'синий', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Gris', 'серый', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Multicolore', 'многокрасочность', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Noir', 'черный', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Orange', 'оранжевый', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Rose', 'розовый', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Vert', 'зеленый', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Violet', 'фиолетовый', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'PRIX', 'цена', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'TAILLES', 'Размеры', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Taille Unique', 'Один размер', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Tailles par âge', 'Размеры возраст', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'TRIER', 'сортировка', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Par Nouveautés', 'по Ново', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Par Prix croissants', 'Увеличивая цены', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Par Prix décroissants', 'По Снижение цен', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Par Taux de remise décroissants', 'За счет снижения ставки дисконтирования', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Mon Compte', 'мой аккаунт', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Mes Coordonnées', 'мой контакт', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Mes Coupons', 'мои купоны', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Se déconnecter', 'Выход', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'panier', 'корзина', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'livraison', 'доставка', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Paiement Sécurisé', 'Безопасная оплата', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'confirmation', 'подтверждение', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'votre panier expire dans', 'корзины истекает', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'minutes', 'минут', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'article expédié par Brandalley', 'товар отправляется в', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Désignation article', 'обозначение изделия', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Prix unitaire TTC', 'Цена за единицу TTC', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Disponibilité', 'доступность', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Offre spéciale', 'специальное предложение', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Quantité', 'количество', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Total TTC', 'Общий НДС', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Montant', 'сумма', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Autre Montant', 'другая сумма', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Coupons disponibles', 'купонов', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Sélectionner', 'выбрать', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Saisir un code promo', 'Введите код купона', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Fermer', 'близко', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Connectez-vous à votre compte', 'Войдите в свой аккаунт', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Mot de passe*', 'Пароль *', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Mot de passe oublié', 'Забыли пароль', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Je souhaite être identifié automatiquement', 'Я хочу, чтобы быть автоматически идентифицирован', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'je me connecte', 'Я вхожу', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'SOUS TOTAL', 'SUBTOTAL', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'TOTAL DE VOTRE COMMANDE	TOTAL', 'вашего заказа', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Poursuivre mes achats', 'Продолжить покупки', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Valider mon panier', 'Корзина и выписка', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Fermer', 'близко', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Supprimer votre article', 'Удалить вашу статью', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Souhaitez-vous supprimer cet article de votre panier', 'Вы хотите удалить этот пункт из корзины', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Annuler', 'отменить', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Confirmer la suppression', 'Подтвердить Удалить', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Paiement sécurisé', 'Безопасная оплата', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Livraison Offerte', 'Имеющаяся поставка', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Retours gratuits', 'свободный возврат', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'sous 30 jours avec le remboursement par avoir', 'в течение 30 дней с погашением при наличии', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Panier unique', 'одна корзина', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'mixe les ventes privées', 'смешанные частные продажи', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'les boutiques', 'магазины', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'Aucun article', 'нет статьи', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'MA WISHLIST', 'МОЙ СПИСОК', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'je découvre', 'посмотреть', '10', NULL, 'new'),
(NULL, CURRENT_TIMESTAMP, 'fr', 'boutiques', 'бутики', '0', NULL, 'new')
;
